--
-- File generated with SQLiteStudio v3.2.1 on Wed Jul 22 20:38:19 2020
--
-- Text encoding used: UTF-8
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: CATEGORY
CREATE TABLE CATEGORY (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, NAME STRING NOT NULL, BUDGET INTEGER NOT NULL DEFAULT (0));

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
