--
-- File generated with SQLiteStudio v3.2.1 on Wed Jul 22 20:38:51 2020
--
-- Text encoding used: UTF-8
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: TRANSACTION
CREATE TABLE "TRANSACTION" (ID INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, NAME STRING NOT NULL, CATEGORY INTEGER REFERENCES CATEGORY (ID) NOT NULL, AMOUNT DECIMAL DEFAULT (0.0) NOT NULL, DESCRIPTION TEXT, DATE DATE NOT NULL);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
